package com.example.guardian.core.model;

import java.util.List;

/**
 * Architecture map generated by Architect Mode.
 *
 * @param modules inferred logical modules
 * @param dependencies module dependencies extracted from imports
 * @param cycles basic cycle detection result
 * @param mermaidDiagram exportable Mermaid module graph
 * @param globalRisks architecture-wide risks
 * @author p15518 - Simone Meneghetti
 */
public record SpringArchitectureMap(
        List<SpringModuleSummary> modules,
        List<SpringModuleDependency> dependencies,
        List<SpringArchitectureCycle> cycles,
        String mermaidDiagram,
        List<String> globalRisks
) {
}
