services:
  spring-guardian-server:
    build:
      context: .
      dockerfile: guardian-server/Dockerfile
    container_name: spring-guardian-server
    environment:
      SPRING_GUARDIAN_API_PREFIX: /api/v1
      SPRING_GUARDIAN_MAX_CONTROLLER_LINES: 35
      SPRING_GUARDIAN_MAX_CONTROLLER_BRANCHES: 8
    volumes:
      - ./sample-projects:/scan:ro
    ports:
      - "8080:8080"

  spring-guardian-ui:
    build:
      context: .
      dockerfile: guardian-ui/Dockerfile
    container_name: spring-guardian-ui
    depends_on:
      - spring-guardian-server
    ports:
      - "3000:80"
