package com.example.guardian.report;

import com.example.guardian.core.model.ArchitectureReviewReport;

/**
 * Renders a structured Spring Guardian report to a concrete output format.
 *
 * @author p15518 - Simone Meneghetti
 */
public interface ReportRenderer {

    /**
     * Renders the supplied report.
     *
     * @param report report generated by guardian-core
     * @return rendered output
     */
    String render(ArchitectureReviewReport report);
}
