package com.example.guardian.core.rules;

import com.example.guardian.core.model.Severity;

import java.util.ArrayList;
import java.util.List;
import java.util.Set;

import static com.example.guardian.core.rules.CatalogPatternRule.Definition.line;
import static com.example.guardian.core.rules.CatalogPatternRule.SourceTarget.CONFIG;
import static com.example.guardian.core.rules.CatalogPatternRule.SourceTarget.JAVA_MAIN;
import static com.example.guardian.core.rules.CatalogPatternRule.SourceTarget.POM;

/**
 * Provides extended deterministic Spring architecture, release-readiness and modernization rule catalogs.
 *
 * @author p15518 - Simone Meneghetti
 */
final class ExtendedRuleCatalogs {

    private ExtendedRuleCatalogs() {
    }

    /**
     * Creates additional Spring architecture and modularity boundary rules.
     *
     * @return architecture rule list
     */
    static List<SpringRule> architectureRules() {
        List<CatalogPatternRule.Definition> definitions = List.of(
                line("ARCH001_DOMAIN_DEPENDS_ON_WEB_LAYER", Severity.MAJOR, JAVA_MAIN, Set.of("org.springframework.web", "responseentity", "httpservletrequest"), "Domain layer depends on web layer", "The domain layer should not depend on HTTP or Spring MVC types. This couples business rules to a delivery mechanism.", "Move web concerns to controllers/adapters and expose domain/application APIs independent from Spring MVC.").inPaths("/domain/"),
                line("ARCH002_DOMAIN_DEPENDS_ON_PERSISTENCE_REPOSITORY", Severity.MAJOR, JAVA_MAIN, Set.of("repository", "jparepository", "crudrepository"), "Domain layer depends on persistence repository", "A DDD or hexagonal domain should not depend on Spring Data repositories directly because persistence becomes part of the model.", "Introduce a domain port or application service and keep Spring Data repositories in infrastructure.").inPaths("/domain/"),
                line("ARCH003_APPLICATION_RETURNS_RESPONSE_ENTITY", Severity.MAJOR, JAVA_MAIN, Set.of("ResponseEntity<", "ResponseEntity."), "Application layer returns web response type", "Application services should represent use cases, not HTTP responses. Returning ResponseEntity leaks the web adapter into the application layer.", "Return application DTOs or domain results from services and map them to ResponseEntity in controllers.").inPaths("/application/", "/service/"),
                line("ARCH004_APPLICATION_DEPENDS_ON_SERVLET_API", Severity.MAJOR, JAVA_MAIN, Set.of("HttpServletRequest", "HttpServletResponse", "jakarta.servlet", "javax.servlet"), "Application layer depends on servlet API", "Servlet types tie application logic to a web runtime and make tests, batch reuse and adapter isolation harder.", "Extract only the required values in the controller/filter and pass application-level parameters to the service.").inPaths("/application/", "/service/"),
                line("ARCH005_INFRASTRUCTURE_CALLED_DIRECTLY_BY_CONTROLLER", Severity.MAJOR, JAVA_MAIN, Set.of("infrastructure.", ".adapter.", "Adapter"), "Controller calls infrastructure adapter directly", "Controllers should delegate to application services. Direct adapter calls bypass use-case orchestration and create unstable boundaries.", "Inject an application service into the controller and let it coordinate infrastructure ports/adapters.").inPaths("/controller/"),
                line("ARCH007_SHARED_ENTITY_ACROSS_MODULES", Severity.MAJOR, JAVA_MAIN, Set.of("@Entity"), "Entity placed in shared/common module", "Shared entities create database-model coupling across modules and make bounded contexts harder to evolve independently.", "Keep entities private to the owning module and expose DTOs/events/contracts across boundaries.").inPaths("/common/", "/shared/"),
                line("ARCH008_API_DTO_REUSED_IN_DOMAIN", Severity.MAJOR, JAVA_MAIN, Set.of("Request", "Response", "Dto"), "API DTO appears in domain layer", "Using API DTOs inside the domain model couples business logic to external contracts.", "Map request/response DTOs at the adapter boundary and keep domain objects independent.").inPaths("/domain/"),
                line("ARCH009_DOMAIN_EVENT_IN_INFRASTRUCTURE", Severity.MINOR, JAVA_MAIN, Set.of("DomainEvent", "Event"), "Domain event declared in infrastructure", "Domain events should describe domain facts and should not be owned by infrastructure packages.", "Move domain event classes to domain/application packages and keep publication mechanics in infrastructure.").inPaths("/infrastructure/", "/adapter/"),
                line("ARCH010_DOMAIN_USES_APPLICATION_EVENT_PUBLISHER", Severity.MAJOR, JAVA_MAIN, Set.of("ApplicationEventPublisher"), "Domain uses Spring event publisher directly", "Publishing Spring application events from domain objects introduces framework coupling and makes domain logic harder to test.", "Return domain events or use an application service to publish events through Spring.").inPaths("/domain/"),
                line("ARCH011_CONFIGURATION_IN_DOMAIN_PACKAGE", Severity.MAJOR, JAVA_MAIN, Set.of("@Configuration", "@Bean"), "Spring configuration placed in domain package", "Configuration classes inside the domain package mix framework bootstrapping with business model code.", "Move Spring configuration to configuration/infrastructure packages.").inPaths("/domain/"),
                line("ARCH012_COMMON_UTIL_DUMPING_GROUND", Severity.MINOR, JAVA_MAIN, Set.of("class ", "static"), "Common utility package may become dumping ground", "Large utility packages with static behavior often hide missing domain concepts and centralize unrelated responsibilities.", "Prefer cohesive services, value objects or module-specific helpers instead of broad shared utility classes.").inPaths("/util/", "/utils/", "/common/"),
                line("ARCH013_HEXAGONAL_PORT_ANNOTATED_AS_SPRING_COMPONENT", Severity.MAJOR, JAVA_MAIN, Set.of("@Component", "@Service", "@Repository"), "Port interface annotated as Spring component", "Ports should normally be plain interfaces; annotating them couples the architectural contract to the Spring container.", "Annotate adapters/implementations, not domain/application ports.").inPaths("/port/", "/ports/"),
                line("ARCH014_ADAPTER_CONTAINS_BUSINESS_TRANSACTION", Severity.MAJOR, JAVA_MAIN, Set.of("@Transactional"), "Adapter owns transactional business boundary", "In layered/hexagonal applications, transaction boundaries usually belong to application services, not external adapters.", "Move the transactional boundary to the use-case service unless the adapter is an infrastructure-only repository implementation.").inPaths("/adapter/", "/controller/"),
                line("ARCH015_PACKAGE_STRUCTURE_DOES_NOT_EXPRESS_MODULES", Severity.MINOR, JAVA_MAIN, Set.of("@SpringBootApplication"), "Application lacks visible architectural package structure", "A project with web, service and persistence capabilities should make module/layer boundaries visible in packages.", "Use package-by-feature or clear controller/application/domain/infrastructure boundaries instead of a flat structure.").excludingPaths("/controller/", "/service/", "/repository/", "/domain/", "/application/", "/infrastructure/")
        );
        return asRules(definitions);
    }

    /**
     * Creates additional Spring Security hardening rules.
     *
     * @return security rule list
     */
    static List<SpringRule> securityRules() {
        List<CatalogPatternRule.Definition> definitions = List.of(
                line("SEC001_ANY_REQUEST_PERMIT_ALL", Severity.CRITICAL, JAVA_MAIN, Set.of("anyRequest().permitAll", "anyRequest().access((authentication, object) -> new AuthorizationDecision(true)"), "All requests are permitted", "A catch-all permit rule disables meaningful authorization and can expose internal endpoints.", "Require authentication by default and allow only explicitly public endpoints.").onlyWhen(c -> c.capabilities().usesSpringSecurity()),
                line("SEC002_WILDCARD_PERMIT_ALL", Severity.CRITICAL, JAVA_MAIN, Set.of("\"/**\"", "'/**'"), "Wildcard security matcher detected", "A /** matcher combined with permitAll or broad ignores can unintentionally expose the entire application.", "Replace /** with explicit public paths and keep the default rule authenticated.").requiringFile("permitAll").onlyWhen(c -> c.capabilities().usesSpringSecurity()),
                line("SEC003_CSRF_DISABLED_WITHOUT_STATELESS", Severity.CRITICAL, JAVA_MAIN, Set.of("csrf", "disable()"), "CSRF disabled without evident stateless policy", "Disabling CSRF is usually acceptable only for stateless APIs or non-browser clients. Otherwise it weakens browser request protection.", "Use SessionCreationPolicy.STATELESS for token APIs or keep CSRF enabled for browser/session flows.").onlyWhen(c -> c.capabilities().usesSpringSecurity()).max(1),
                line("SEC004_CORS_WILDCARD_WITH_CREDENTIALS", Severity.CRITICAL, JAVA_MAIN, Set.of("setAllowCredentials(true)", "allowCredentials(true)"), "CORS credentials enabled", "Credentials with broad origins can expose authenticated APIs cross-origin.", "Use explicit allowed origins or origin patterns and avoid wildcard credentials.").requiringFile("*").onlyWhen(c -> c.capabilities().usesSpringSecurity()),
                line("SEC005_ACTUATOR_EXPOSE_ALL", Severity.MAJOR, CONFIG, Set.of("management.endpoints.web.exposure.include=*", "management.endpoints.web.exposure.include: \"*\"", "management.endpoints.web.exposure.include: '*'"), "All actuator endpoints exposed", "Exposing every actuator endpoint can leak sensitive operational data or permit risky operations.", "Expose only required endpoints such as health/info/metrics and protect them with management security.").onlyWhen(c -> c.capabilities().usesActuator()),
                line("SEC006_FORM_LOGIN_IN_REST_API", Severity.MAJOR, JAVA_MAIN, Set.of("formLogin("), "Form login enabled in REST API", "Form login is often not aligned with stateless REST API authentication and can create unexpected browser/session behavior.", "Disable formLogin for token/resource-server APIs or isolate it in a dedicated browser security chain.").onlyWhen(c -> c.capabilities().usesSpringWeb()),
                line("SEC007_HTTP_BASIC_IN_PRODUCTION", Severity.MAJOR, JAVA_MAIN, Set.of("httpBasic("), "HTTP Basic enabled", "HTTP Basic may be acceptable for internal tooling but should be explicit and carefully protected in production APIs.", "Prefer OAuth2 Resource Server, mTLS or a documented internal security policy for production APIs.").onlyWhen(c -> c.profile().releaseTarget().name().equals("PRODUCTION")),
                line("SEC008_REMEMBER_ME_IN_REST_API", Severity.MAJOR, JAVA_MAIN, Set.of("rememberMe("), "Remember-me enabled in API", "Remember-me cookies are a browser session feature and do not fit stateless REST APIs.", "Remove rememberMe for REST APIs or isolate it in a browser-only security chain.").onlyWhen(c -> c.capabilities().usesSpringWeb()),
                line("SEC009_FRAME_OPTIONS_DISABLED", Severity.MAJOR, JAVA_MAIN, Set.of("frameOptions", "disable()"), "Frame options disabled", "Disabling frame options outside dev/H2 scenarios can re-enable clickjacking risks.", "Keep frame options enabled, and restrict exceptions to dev/test H2 console configuration.").requiringFile("frameOptions"),
                line("SEC010_H2_CONSOLE_EXPOSED_OUTSIDE_TEST", Severity.MAJOR, CONFIG, Set.of("spring.h2.console.enabled=true", "spring.h2.console.enabled: true"), "H2 console enabled", "The H2 console should not be enabled in production-like packaged configuration.", "Enable H2 console only under dev/test profiles and never in production runtime configuration.").onlyWhen(c -> c.profile().releaseTarget().name().equals("PRODUCTION")),
                line("SEC011_SWAGGER_EXPOSED_IN_PRODUCTION", Severity.MINOR, CONFIG, Set.of("springdoc.swagger-ui.enabled=true", "springdoc.api-docs.enabled=true"), "Swagger explicitly enabled", "Public API documentation may be useful, but internal operations often require profile or role-based access.", "Protect Swagger/OpenAPI in production or expose only when intentionally allowed.").onlyWhen(c -> c.profile().releaseTarget().name().equals("PRODUCTION")),
                line("SEC012_SECRET_KEY_HARDCODED", Severity.CRITICAL, JAVA_MAIN, Set.of("SecretKeySpec", "signingKey", "jwtSecret", "secretKey"), "Security secret appears hardcoded or locally created", "Cryptographic keys and token secrets must be externally managed and rotated.", "Load secrets from environment, Vault, secret manager or deployment secret configuration.").max(2),
                line("SEC013_NOOP_PASSWORD_ENCODER", Severity.CRITICAL, JAVA_MAIN, Set.of("NoOpPasswordEncoder"), "NoOpPasswordEncoder detected", "NoOp password encoding stores or compares raw passwords and is not production safe.", "Use a central PasswordEncoder bean such as BCryptPasswordEncoder with an approved strength.").onlyWhen(c -> c.capabilities().usesSpringSecurity()),
                line("SEC015_SECURITY_CONTEXT_IN_REPOSITORY", Severity.MAJOR, JAVA_MAIN, Set.of("SecurityContextHolder"), "Repository reads security context", "Repositories should not know about authenticated users. This couples persistence to security runtime state.", "Resolve user context in controller/application service and pass explicit values to persistence methods.").inPaths("/repository/"),
                line("SEC016_HARDCODED_ROLE_STRING", Severity.MINOR, JAVA_MAIN, Set.of("ROLE_", "hasRole(\"", "hasAuthority(\""), "Hardcoded role or authority string", "Scattered role strings make authorization policy hard to audit and refactor.", "Centralize authorities/scopes in constants or a domain authorization policy.").max(3),
                line("SEC017_PERMIT_ALL_ON_MUTATING_PATH", Severity.CRITICAL, JAVA_MAIN, Set.of("permitAll"), "permitAll may protect mutating endpoint", "Mutating endpoints should rarely be public. A broad permitAll on POST/PUT/DELETE paths is a release blocker.", "Keep public access limited to documented read-only or authentication endpoints.").requiringFile("post", "delete").onlyWhen(c -> c.capabilities().usesSpringSecurity()),
                line("SEC018_CORS_CONFIG_IN_CONTROLLER", Severity.MINOR, JAVA_MAIN, Set.of("@CrossOrigin"), "CORS configured directly on controller", "Scattered CORS annotations make environment-specific security policy hard to audit.", "Centralize CORS policy in CorsConfigurationSource or WebMvcConfigurer.").onlyWhen(c -> c.capabilities().usesSpringWeb()),
                line("SEC019_CUSTOM_FILTER_WITHOUT_ORDER", Severity.MINOR, JAVA_MAIN, Set.of("OncePerRequestFilter", "GenericFilterBean"), "Custom security/filter component detected", "Custom filters require clear registration order and error behavior to avoid bypass or duplicated execution.", "Register filters through the SecurityFilterChain or FilterRegistrationBean with explicit ordering and tests.").onlyWhen(c -> c.capabilities().usesSpringSecurity()),
                line("SEC020_SECURITY_EXCEPTION_CATCH_ALL", Severity.MAJOR, JAVA_MAIN, Set.of("AuthenticationException", "AccessDeniedException"), "Security exception handled manually", "Manual security exception handling can bypass consistent entry points and access denied handlers.", "Use AuthenticationEntryPoint, AccessDeniedHandler or Spring Security exception handling configuration.").max(2)
        );
        return asRules(definitions);
    }

    /**
     * Creates additional Web/API contract rules.
     *
     * @return Web/API rule list
     */
    static List<SpringRule> webApiRules() {
        List<CatalogPatternRule.Definition> definitions = List.of(
                line("WEB001_SERVICE_RETURNS_RESPONSE_ENTITY", Severity.MAJOR, JAVA_MAIN, Set.of("ResponseEntity<", "ResponseEntity."), "Service returns ResponseEntity", "ResponseEntity belongs to the web adapter. Returning it from services leaks HTTP concerns into application logic.", "Return application DTOs/results from services and build ResponseEntity in controllers.").inPaths("/service/", "/application/"),
                line("WEB002_SERVICE_USES_SERVLET_API", Severity.MAJOR, JAVA_MAIN, Set.of("HttpServletRequest", "HttpServletResponse", "ServletRequest"), "Service uses servlet API", "Servlet dependencies make services difficult to reuse from batch, messaging or tests.", "Extract request data in the controller/filter and pass domain/application parameters.").inPaths("/service/", "/application/"),
                line("WEB003_CONTROLLER_TRY_CATCH_TECHNICAL", Severity.MINOR, JAVA_MAIN, Set.of("try {", "catch (Exception", "catch(Exception"), "Controller handles technical exceptions locally", "Technical try/catch in controllers causes inconsistent API errors and duplicates error mapping.", "Use @RestControllerAdvice with ProblemDetail/ErrorResponse for centralized error handling.").inPaths("/controller/").max(2),
                line("WEB004_EXCEPTION_MESSAGE_EXPOSED", Severity.MAJOR, JAVA_MAIN, Set.of("getMessage()"), "API may expose raw exception message", "Raw exception messages can leak technical details or unstable internal wording to clients.", "Map exceptions to stable error codes/messages through @ControllerAdvice.").inPaths("/controller/"),
                line("WEB005_PAGE_ENTITY_EXPOSED", Severity.MAJOR, JAVA_MAIN, Set.of("Page<"), "Page response exposed directly", "Exposing Page<Entity> can leak persistence model and Spring Data response structure as a public contract.", "Map paged data to DTO pages or dedicated response wrappers.").requiringFile("@RestController"),
                line("WEB006_PAGEABLE_WITHOUT_LIMIT_POLICY", Severity.MINOR, JAVA_MAIN, Set.of("Pageable"), "Pageable accepted without visible limit policy", "Unbounded or uncontrolled pageable/sort inputs can create heavy queries or unstable API behavior.", "Apply default/max page sizes and whitelist sortable fields where relevant.").inPaths("/controller/").max(2),
                line("WEB007_SORT_INPUT_DIRECTLY_EXPOSED", Severity.MINOR, JAVA_MAIN, Set.of("Sort"), "Sort accepted directly from API", "Free sorting can expose internal field names and trigger inefficient database access.", "Whitelist sortable fields or map public sort keys to persistence fields.").inPaths("/controller/").max(2),
                line("WEB008_OBJECT_RESPONSE", Severity.MAJOR, JAVA_MAIN, Set.of("ResponseEntity<Object>", "public Object "), "Generic Object response", "Generic API responses hide the contract from OpenAPI, clients and tests.", "Use explicit response DTOs or ProblemDetail for errors.").inPaths("/controller/"),
                line("WEB009_MAP_RESPONSE", Severity.MINOR, JAVA_MAIN, Set.of("Map<String, Object>", "Map<String,Object>"), "Map response used as API contract", "Maps are flexible but weakly typed and make contracts harder to document and validate.", "Use explicit DTOs for stable public responses.").inPaths("/controller/"),
                line("WEB010_BULK_ENDPOINT_WITHOUT_LIMIT", Severity.MAJOR, JAVA_MAIN, Set.of("/bulk", "bulk"), "Bulk endpoint detected", "Bulk endpoints need explicit limits, validation and operational protection to avoid excessive load.", "Document and enforce maximum payload size, transaction boundaries and partial failure behavior.").inPaths("/controller/").max(1),
                line("WEB011_MUTATING_GET_MAPPING", Severity.CRITICAL, JAVA_MAIN, Set.of("@GetMapping"), "GET endpoint appears to mutate state", "GET must be safe and idempotent from an HTTP contract perspective. Mutating GET endpoints break caches and client assumptions.", "Use POST/PUT/PATCH/DELETE for state changes and reserve GET for reads.").requiringFile("save", "delete"),
                line("WEB012_POST_WITHOUT_VALID", Severity.MAJOR, JAVA_MAIN, Set.of("@PostMapping", "@PutMapping", "@PatchMapping"), "Mutating endpoint should validate input", "Mutating endpoints without @Valid or @Validated can let invalid data reach application logic.", "Apply @Valid to request DTOs and Bean Validation annotations to fields.").requiringFile("@RequestBody").inPaths("/controller/"),
                line("WEB013_OPENAPI_MISSING_ON_PUBLIC_CONTROLLER", Severity.MINOR, JAVA_MAIN, Set.of("@RestController"), "Public controller should be documented", "Public REST APIs should be understandable through generated OpenAPI contracts.", "Add @Operation/@ApiResponse on public endpoints or document why the controller is internal.").onlyWhen(c -> c.capabilities().usesOpenApi()).max(1),
                line("WEB014_ADMIN_ENDPOINT_MIXED_WITH_PUBLIC", Severity.MINOR, JAVA_MAIN, Set.of("admin"), "Admin endpoint mixed into regular controller", "Administration endpoints have different authorization, audit and operational expectations than public API endpoints.", "Separate admin controllers and secure them with explicit roles/policies.").inPaths("/controller/"),
                line("WEB015_DTO_IN_ENTITY_PACKAGE", Severity.MINOR, JAVA_MAIN, Set.of("Dto", "Request", "Response"), "DTO placed near entity package", "Mixing API DTOs with entities blurs persistence and API boundaries.", "Move DTOs to api/dto/web contract packages and map them explicitly.").inPaths("/entity/", "/model/"),
                line("WEB016_MANUAL_VALIDATION_IN_CONTROLLER", Severity.MINOR, JAVA_MAIN, Set.of("if (", "isBlank()", "== null"), "Manual validation in controller", "Manual validation inside controllers often becomes inconsistent and hard to expose through OpenAPI.", "Prefer Bean Validation annotations and @Valid/@Validated.").inPaths("/controller/").max(2),
                line("WEB017_RESPONSE_STATUS_MISSING_ON_CREATE", Severity.MINOR, JAVA_MAIN, Set.of("@PostMapping"), "POST create endpoint may lack explicit status", "Creation endpoints should intentionally return 201, 202 or 204 where appropriate rather than defaulting to 200.", "Use ResponseEntity.created, @ResponseStatus(CREATED), or a documented response policy.").inPaths("/controller/").max(2),
                line("WEB018_DELETE_ENDPOINT_WITH_BODY", Severity.MINOR, JAVA_MAIN, Set.of("@DeleteMapping"), "DELETE endpoint should use clear response semantics", "DELETE endpoints should have explicit idempotency and status behavior.", "Prefer 204 for successful deletion or a documented DTO when returning status information.").inPaths("/controller/").max(2),
                line("WEB019_NO_CONSUMES_FOR_MULTIPART", Severity.MINOR, JAVA_MAIN, Set.of("MultipartFile"), "Multipart endpoint without visible media contract", "Multipart APIs need explicit size limits and content-type expectations.", "Configure multipart limits and document consumes = multipart/form-data.").inPaths("/controller/"),
                line("WEB020_REPOSITORY_IN_CONTROLLER", Severity.MAJOR, JAVA_MAIN, Set.of("Repository"), "Controller depends on repository", "The controller should not bypass application service boundaries.", "Inject a service/use-case component instead of a repository.").inPaths("/controller/")
        );
        return asRules(definitions);
    }

    /**
     * Creates additional Spring Batch operational readiness rules.
     *
     * @return batch rule list
     */
    static List<SpringRule> batchRules() {
        List<CatalogPatternRule.Definition> definitions = List.of(
                line("BAT001_JOB_WITHOUT_PARAMETERS_VALIDATOR", Severity.MINOR, JAVA_MAIN, Set.of("new JobBuilder", "JobBuilder("), "Job should declare parameter validation", "Batch jobs depend on stable identifying parameters. Missing validation creates failed or duplicate executions.", "Add a JobParametersValidator for mandatory and identifying parameters.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT002_CHUNK_SIZE_HARDCODED", Severity.MINOR, JAVA_MAIN, Set.of(".chunk(", "chunk("), "Chunk size appears hardcoded", "Chunk size affects memory, transaction duration and throughput and should be tuned per environment/job.", "Externalize chunk size through configuration properties and document defaults.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT003_PAGING_READER_WITHOUT_SORT", Severity.MAJOR, JAVA_MAIN, Set.of("JdbcPagingItemReader"), "Paging reader requires stable sort key", "JdbcPagingItemReader needs deterministic ordering for restartability and correct pagination.", "Configure a stable sort key on immutable/unique columns.").onlyWhen(c -> c.capabilities().usesSpringBatch()).max(2),
                line("BAT004_CURSOR_READER_ON_BATCH", Severity.MINOR, JAVA_MAIN, Set.of("JdbcCursorItemReader"), "Cursor reader detected", "Cursor readers can be valid but may hold database resources for long-running jobs.", "Evaluate JdbcPagingItemReader for large datasets and document cursor use when intentional.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT005_READER_SELECT_STAR", Severity.MINOR, JAVA_MAIN, Set.of("select *"), "Batch reader uses SELECT *", "SELECT * makes batch DTOs fragile and may read unnecessary columns on large datasets.", "Select only required columns and keep mapper/DTO aligned.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT006_PROCESSOR_STATEFUL_FIELD", Severity.MAJOR, JAVA_MAIN, Set.of("ItemProcessor"), "ItemProcessor should be stateless", "Stateful processors can break restartability and parallel execution.", "Keep processors stateless or isolate state in ExecutionContext with clear serialization semantics.").requiringFile("private ").onlyWhen(c -> c.capabilities().usesSpringBatch()).max(2),
                line("BAT007_RETRY_ON_GENERIC_EXCEPTION", Severity.MAJOR, JAVA_MAIN, Set.of(".retry(Exception.class)", "retry(Exception.class)", "retry(Throwable.class)"), "Generic retry in batch", "Retrying every exception can repeat non-transient failures and hide data problems.", "Retry only transient exceptions and configure backoff/limits.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT008_SKIP_ON_GENERIC_EXCEPTION", Severity.MAJOR, JAVA_MAIN, Set.of(".skip(Exception.class)", "skip(Exception.class)", "skip(Throwable.class)"), "Generic skip in batch", "Skipping generic exceptions can silently discard business-critical data.", "Skip only known recoverable exceptions and log skipped items through SkipListener.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT009_FAULT_TOLERANCE_WITHOUT_LISTENER", Severity.MINOR, JAVA_MAIN, Set.of("faultTolerant()"), "Fault tolerance should be observable", "Fault-tolerant steps need skip/retry visibility for operations and audit.", "Add SkipListener/RetryListener and expose counters in logs or metrics.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT010_EXECUTION_CONTEXT_COMPLEX_OBJECT", Severity.MAJOR, JAVA_MAIN, Set.of("ExecutionContext"), "ExecutionContext usage detected", "ExecutionContext should store small serializable restart metadata, not large or non-serializable objects.", "Store primitive/string metadata and persist large state in durable business tables.").onlyWhen(c -> c.capabilities().usesSpringBatch()).max(2),
                line("BAT011_RUN_ID_INCREMENTER_RESTARTABILITY", Severity.MINOR, JAVA_MAIN, Set.of("RunIdIncrementer"), "RunIdIncrementer detected", "RunIdIncrementer is useful, but it can hide unclear identifying parameters and restart semantics.", "Use explicit identifying JobParameters and document when a new instance is required.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT012_ALLOW_START_IF_COMPLETE", Severity.MAJOR, JAVA_MAIN, Set.of("allowStartIfComplete(true)"), "Step allowed to rerun after completion", "Rerunning a completed step is safe only when the step is idempotent.", "Use allowStartIfComplete only for idempotent steps and document why.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT013_TASK_EXECUTOR_IN_STEP", Severity.MAJOR, JAVA_MAIN, Set.of("taskExecutor("), "Parallel batch step detected", "Parallel steps require thread-safe readers, processors and writers.", "Verify thread safety, throttle/grid size and shared mutable state before enabling parallel execution.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT014_GRID_SIZE_HARDCODED", Severity.MINOR, JAVA_MAIN, Set.of("gridSize("), "Grid size appears hardcoded", "Grid size should match runtime capacity and deployment resources.", "Externalize grid size and tune it with executor configuration.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT015_SYSTEM_EXIT_IN_BATCH", Severity.CRITICAL, JAVA_MAIN, Set.of("System.exit("), "System.exit inside batch", "System.exit bypasses Spring Batch lifecycle, transaction handling and scheduler control.", "Return ExitStatus/BatchStatus and let the launcher/scheduler decide process behavior.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT016_THREAD_SLEEP_IN_BATCH", Severity.MAJOR, JAVA_MAIN, Set.of("Thread.sleep("), "Thread.sleep in batch component", "Sleeping inside batch code wastes worker threads and makes retry/backoff invisible.", "Use retry/backoff policies, scheduler delays or controlled polling abstractions.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT017_WRITER_CONTAINS_BUSINESS_LOGIC", Severity.MINOR, JAVA_MAIN, Set.of("ItemWriter"), "Writer should focus on output", "Putting transformation/business decisions in writers makes retries and testing harder.", "Move transformation to processor/service and keep writers focused on durable output.").requiringFile("if (").onlyWhen(c -> c.capabilities().usesSpringBatch()).max(2),
                line("BAT018_PROCESSOR_REMOTE_CALL_PER_ITEM", Severity.MAJOR, JAVA_MAIN, Set.of("ItemProcessor"), "Processor may call remote services per item", "Remote calls per item can destroy throughput and make failures hard to handle.", "Batch remote calls, cache reference data or move integration to chunk-aware service logic.").requiringFile("RestClient", "WebClient").onlyWhen(c -> c.capabilities().usesSpringBatch()).max(2),
                line("BAT019_STEP_NAME_GENERIC", Severity.INFO, JAVA_MAIN, Set.of("step1", "step2", "job1"), "Generic batch job or step name", "Operational dashboards and restart procedures need meaningful job/step names.", "Use stable functional names that describe the batch responsibility.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("BAT020_EXIT_STATUS_NOT_CUSTOMIZED", Severity.INFO, JAVA_MAIN, Set.of("ExitStatus"), "Custom ExitStatus detected", "Custom exit statuses are useful but must be consistently mapped by schedulers and operators.", "Document partial, warning and failed statuses and map them in orchestration.").onlyWhen(c -> c.capabilities().usesSpringBatch())
        );
        return asRules(definitions);
    }

    /**
     * Creates cloud readiness and 12-factor inspired rules.
     *
     * @return cloud readiness rule list
     */
    static List<SpringRule> cloudRules() {
        List<CatalogPatternRule.Definition> definitions = List.of(
                line("CLD001_ENVIRONMENT_URL_IN_CONFIG", Severity.MAJOR, CONFIG, Set.of("http://", "https://", "jdbc:"), "Environment URL packaged in config", "Packaged artifacts should remain environment-neutral. Runtime URLs belong to deployment configuration.", "Use placeholders, environment variables, ConfigMap/Secret, Vault or platform configuration.").inPaths("src/main/resources"),
                line("CLD002_ACTIVE_PROFILE_COMMITTED", Severity.MAJOR, CONFIG, Set.of("spring.profiles.active"), "Active Spring profile committed", "Committing active profiles couples the artifact to an environment and can accidentally run prod/test behavior.", "Set active profiles from deployment/runtime, not from packaged configuration.").inPaths("src/main/resources"),
                line("CLD003_SECRET_IN_CONFIG", Severity.CRITICAL, CONFIG, Set.of("password=", "password:", "secret=", "token=", "apikey", "api-key"), "Secret-like value in packaged configuration", "Secrets in repository/config packages are hard to rotate and can leak to developers, builds or artifacts.", "Move secrets to environment variables, Vault, secret manager or deployment secrets.").inPaths("src/main/resources"),
                line("CLD004_ABSOLUTE_PATH", Severity.MAJOR, CONFIG, Set.of("c:\\", "/var/", "/tmp/", "/home/"), "Absolute runtime path in configuration", "Absolute paths tie the artifact to a host and break container/cloud portability.", "Externalize paths or use mounted volumes/resources documented per environment.").inPaths("src/main/resources"),
                line("CLD005_LOG_FILE_LOCAL", Severity.MAJOR, CONFIG, Set.of("logging.file.name", "logging.file.path"), "Application logs written to local file", "Cloud-native runtimes expect logs on stdout/stderr for collection and correlation.", "Prefer console logging and central aggregation; use file logs only when the platform requires it.").inPaths("src/main/resources"),
                line("CLD006_HTTP_SESSION_STATE", Severity.MAJOR, JAVA_MAIN, Set.of("HttpSession", "@SessionAttributes"), "Local HTTP session state detected", "Local sessions complicate horizontal scaling unless backed by a shared session store.", "Prefer stateless tokens or configure Spring Session/shared session storage.").onlyWhen(c -> c.capabilities().usesSpringWeb()),
                line("CLD007_LOCAL_CACHE_STATE", Severity.MINOR, JAVA_MAIN, Set.of("static Map", "ConcurrentHashMap"), "Local in-memory state detected", "Local process state can become inconsistent across multiple instances.", "Use Spring Cache with a suitable cache manager or a shared backing service for distributed state.").max(2),
                line("CLD008_HARDCODED_HOST_IN_JAVA", Severity.MAJOR, JAVA_MAIN, Set.of("http://", "https://", "jdbc:"), "Host or endpoint hardcoded in Java", "Hardcoded infrastructure values prevent environment-neutral releases.", "Bind endpoints through validated @ConfigurationProperties.").max(3),
                line("CLD009_FEATURE_FLAG_HARDCODED", Severity.MINOR, JAVA_MAIN, Set.of("feature", "enabled = true", "enabled = false"), "Feature flag appears hardcoded", "Hardcoded switches require redeploys and make rollout control difficult.", "Use configuration properties or a feature flag service/policy.").max(2),
                line("CLD010_CONFIGURATION_PROPERTIES_WITHOUT_VALIDATION", Severity.MINOR, JAVA_MAIN, Set.of("@ConfigurationProperties"), "Configuration properties should be validated", "Configuration objects without validation can fail late or accept incomplete runtime settings.", "Add @Validated and Bean Validation constraints for required properties.").requiringFile("class ").max(2),
                line("CLD011_HEALTH_ENDPOINT_NOT_CONFIGURED", Severity.MINOR, CONFIG, Set.of("management.endpoint.health"), "Health endpoint customization detected", "Health configuration should distinguish operational readiness from generic liveness in production.", "Enable health probes and define readiness/liveness when deploying to orchestrated environments.").max(1),
                line("CLD012_GRACEFUL_SHUTDOWN_MISSING", Severity.INFO, CONFIG, Set.of("server.shutdown"), "Graceful shutdown setting detected", "Graceful shutdown improves rolling deployments when tuned with timeout and workload behavior.", "Ensure server.shutdown=graceful and lifecycle timeout are configured for production.").max(1),
                line("CLD013_TIMEOUT_NOT_VISIBLE_ON_CLIENT", Severity.MINOR, JAVA_MAIN, Set.of("RestClient", "WebClient", "RestTemplate"), "HTTP client should have timeout policy", "HTTP clients without central timeout configuration can hang threads and degrade upstream services.", "Configure connect/read/response timeouts in the shared client builder.").max(2),
                line("CLD014_BATCH_RUNTIME_PATH_NOT_EXTERNALIZED", Severity.MAJOR, CONFIG, Set.of("input.file", "output.file", "batch.file", "file.path"), "Batch file path packaged in config", "Batch input/output paths are runtime concerns and differ between environments.", "Externalize batch paths through deployment configuration and document volume mounts.").onlyWhen(c -> c.capabilities().usesSpringBatch()),
                line("CLD015_PROFILE_SPECIFIC_PROD_CONFIG_COMMITTED", Severity.MAJOR, CONFIG, Set.of("application-prod", "prod:"), "Production profile configuration committed", "Production-specific values in packaged source increase risk of accidental environment coupling or secret leakage.", "Keep only safe defaults/placeholders in the repository and inject prod values at deploy time.").inPaths("src/main/resources")
        );
        return asRules(definitions);
    }

    /**
     * Creates observability, logging and operational diagnostics rules.
     *
     * @return observability rule list
     */
    static List<SpringRule> observabilityRules() {
        List<CatalogPatternRule.Definition> definitions = List.of(
                line("OBS001_SYSTEM_OUT", Severity.MINOR, JAVA_MAIN, Set.of("System.out.println", "System.err.println"), "Console print used instead of logger", "Direct console printing bypasses levels, correlation and structured logging policy.", "Use SLF4J Logger and include contextual fields through the logging policy.").max(3),
                line("OBS002_PRINT_STACK_TRACE", Severity.MAJOR, JAVA_MAIN, Set.of("printStackTrace()"), "printStackTrace used", "printStackTrace loses structured context and may expose implementation details.", "Log exceptions with a logger and propagate or map them consistently.").max(3),
                line("OBS004_MDC_USAGE", Severity.MINOR, JAVA_MAIN, Set.of("MDC.put"), "MDC usage detected", "MDC is useful but must be cleaned to avoid leaking correlation data between requests on reused threads.", "Use try/finally with MDC.clear/remove or a servlet filter/interceptor that guarantees cleanup.").max(2),
                line("OBS005_SENSITIVE_LOG_KEY", Severity.CRITICAL, JAVA_MAIN, Set.of("password", "token", "secret", "authorization"), "Sensitive data may be logged", "Logs are often centralized and widely accessible; sensitive values must not be written to logs.", "Mask or remove secrets/tokens/passwords from log messages and audit events.").requiringLine("log.").max(3),
                line("OBS006_MANUAL_METRIC_COUNTER", Severity.MINOR, JAVA_MAIN, Set.of("counter++", "count++"), "Manual counter detected", "Manual counters are invisible to monitoring systems and reset on restart.", "Use Micrometer MeterRegistry counters/timers/gauges for operational metrics.").max(2),
                line("OBS007_HEALTH_CONTROLLER", Severity.MINOR, JAVA_MAIN, Set.of("/health", "health"), "Custom health endpoint may duplicate Actuator", "Custom health controllers often miss standard readiness/liveness semantics and security integration.", "Use Actuator HealthIndicator and health groups for operational checks.").inPaths("/controller/").max(1),
                line("OBS008_BATCH_NO_COUNTERS", Severity.INFO, JAVA_MAIN, Set.of("ItemWriteListener", "JobExecutionListener", "StepExecutionListener"), "Batch listener detected", "Batch listeners should expose read/write/skip counts and duration for operations.", "Log and/or publish Micrometer metrics for batch execution counts and duration.").onlyWhen(c -> c.capabilities().usesSpringBatch()).max(1),
                line("OBS009_REQUEST_ID_HEADER", Severity.INFO, JAVA_MAIN, Set.of("X-Request-Id", "X-Correlation-Id"), "Correlation header detected", "Correlation IDs improve diagnostics only when consistently propagated to logs and downstream clients.", "Standardize request/correlation ID handling in a filter/interceptor and HTTP client configuration.").max(1),
                line("OBS010_HEALTH_DETAILS_EXPOSED", Severity.MAJOR, CONFIG, Set.of("management.endpoint.health.show-details=always", "show-details: always"), "Health details exposed", "Detailed health output can reveal internal infrastructure and dependency names.", "Use show-details=when_authorized or restrict details to internal/admin access.").onlyWhen(c -> c.profile().releaseTarget().name().equals("PRODUCTION"))
        );
        return asRules(definitions);
    }

    /**
     * Creates additional Spring Alternative Advisor rules.
     *
     * @return advisor rule list
     */
    static List<SpringRule> advisorRules() {
        List<CatalogPatternRule.Definition> definitions = List.of(
                line("ADV001_MANUAL_RETRY_LOOP", Severity.MINOR, JAVA_MAIN, Set.of("for (", "while ("), "Manual retry or polling loop", "Manual retry loops often lack backoff, observability and clear failure policy.", "Use Spring Retry or Resilience4j with explicit retry/backoff policies.").requiringFile("try", "catch").max(2),
                line("ADV002_MANUAL_CIRCUIT_BREAKER", Severity.MINOR, JAVA_MAIN, Set.of("circuit", "fallback"), "Manual resilience logic detected", "Hand-built resilience logic is hard to tune and observe consistently.", "Evaluate Resilience4j/Spring integration for circuit breaker, retry and timeout policies.").max(2),
                line("ADV003_MANUAL_HEALTH_CONTROLLER", Severity.MINOR, JAVA_MAIN, Set.of("@GetMapping", "/health"), "Manual health endpoint", "Manual health endpoints usually duplicate Actuator and may not integrate with readiness/liveness groups.", "Implement HealthIndicator or configure Actuator health groups.").inPaths("/controller/"),
                line("ADV004_MANUAL_METRICS", Severity.MINOR, JAVA_MAIN, Set.of("long start", "System.currentTimeMillis", "nanoTime"), "Manual timing/metrics detected", "Manual timings disappear from metrics backends and lack tags/correlation.", "Use Micrometer Timer/Observation for measured operations.").max(3),
                line("ADV005_MANUAL_AUDIT_SCATTERED", Severity.MINOR, JAVA_MAIN, Set.of("audit", "Audit"), "Manual audit logic detected", "Audit writes scattered across services become inconsistent and hard to evolve.", "Centralize auditing through events/listeners or a dedicated audit service abstraction.").max(3),
                line("ADV006_APPLICATION_EVENT_PUBLISHER_ALTERNATIVE", Severity.INFO, JAVA_MAIN, Set.of("ApplicationEventPublisher"), "Application events detected", "Application events are useful but should represent clear application/domain facts and have observable listeners.", "Keep event contracts explicit and test listener behavior.").max(2),
                line("ADV009_MESSAGE_SOURCE_ALTERNATIVE", Severity.INFO, JAVA_MAIN, Set.of("Locale", "ResourceBundle"), "Manual localization detected", "Manual localization maps/resource bundles can bypass Spring MessageSource policy.", "Use MessageSource and locale resolution configured by Spring.").max(2),
                line("ADV010_FILTER_REGISTRATION_ALTERNATIVE", Severity.MINOR, JAVA_MAIN, Set.of("FilterRegistrationBean", "OncePerRequestFilter"), "Filter registration detected", "Filters are valid but need explicit ordering and scope to avoid interfering with Spring Security or observability.", "Register filters centrally with explicit order, URL patterns and tests.").max(2),
                line("ADV011_WEBMVC_CONFIGURER_ALTERNATIVE", Severity.INFO, JAVA_MAIN, Set.of("HandlerInterceptor"), "Interceptor detected", "Interceptors should be registered centrally for predictable ordering and path matching.", "Register HandlerInterceptor through WebMvcConfigurer and document path patterns.").max(2),
                line("ADV012_MANUAL_CORS_ANNOTATION", Severity.MINOR, JAVA_MAIN, Set.of("@CrossOrigin"), "Controller-level CORS annotation", "Controller-level CORS can fragment environment/security policy.", "Centralize CORS through CorsConfigurationSource or WebMvcConfigurer.").max(3),
                line("ADV013_JACKSON_CUSTOMIZER_ALTERNATIVE", Severity.INFO, JAVA_MAIN, Set.of("JavaTimeModule", "SimpleModule"), "Manual Jackson module registration", "Manual module registration in random classes can diverge from Boot's global ObjectMapper.", "Use Jackson2ObjectMapperBuilderCustomizer or ObjectMapper bean customization.").max(2),
                line("ADV014_ENUM_PARSING_CONVERTER", Severity.INFO, JAVA_MAIN, Set.of("Enum.valueOf"), "Manual enum parsing", "Manual enum parsing can produce inconsistent API errors and case policies.", "Use Converter/Formatter or request DTO validation for explicit conversion behavior.").max(2),
                line("ADV015_COMPLETABLE_FUTURE_COMMON_POOL", Severity.MAJOR, JAVA_MAIN, Set.of("CompletableFuture.supplyAsync", "CompletableFuture.runAsync"), "CompletableFuture uses default executor", "Default common-pool async work bypasses Spring executor configuration, naming and observability.", "Inject a configured TaskExecutor or use @Async with an explicit executor.").max(3),
                line("ADV016_SCHEDULED_EXECUTOR_SERVICE", Severity.MAJOR, JAVA_MAIN, Set.of("ScheduledExecutorService", "newScheduledThreadPool"), "Scheduled executor created manually", "Manual scheduled executors bypass Spring lifecycle and shutdown control.", "Use TaskScheduler or @Scheduled with centralized scheduling configuration.").max(3),
                line("ADV017_MANUAL_CACHE_EVICTION", Severity.MINOR, JAVA_MAIN, Set.of("remove(", "clear()"), "Manual cache eviction detected", "Manual cache maps are hard to observe, configure and invalidate consistently.", "Use Spring Cache annotations such as @Cacheable and @CacheEvict when the data is cacheable.").requiringFile("Map").max(2),
                line("ADV018_FLYWAY_LIQUIBASE_ALTERNATIVE", Severity.MAJOR, JAVA_MAIN, Set.of("schema.sql", "data.sql", "executeUpdate("), "Manual database initialization/migration", "Manual schema changes at startup are risky and hard to audit.", "Use Flyway or Liquibase for versioned database migrations.").max(2),
                line("ADV019_PROFILE_IF_ELSE", Severity.MINOR, JAVA_MAIN, Set.of("getActiveProfiles", "acceptsProfiles"), "Manual profile branching", "Manual environment branching scatters deployment behavior across code.", "Use @Profile, @ConditionalOnProperty or typed configuration properties.").max(2)
        );
        return asRules(definitions);
    }

    private static List<SpringRule> asRules(List<CatalogPatternRule.Definition> definitions) {
        List<SpringRule> rules = new ArrayList<>();
        definitions.forEach(definition -> rules.add(new CatalogPatternRule(definition)));
        return List.copyOf(rules);
    }
}
