package com.example.guardian.core;

import com.example.guardian.core.config.GuardianSettings;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.io.TempDir;

import java.nio.file.Files;
import java.nio.file.Path;

import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Verifies production readiness, upgrade path and OpenRewrite suggestions generated by Architect Mode.
 *
 * @author p15518 - Simone Meneghetti
 */
class ArchitectModeProductionUpgradeOpenRewriteTest {

    @TempDir
    Path tempDir;

    @Test
    void createsProductionUpgradeAndOpenRewriteRoadmapFromLegacySignals() throws Exception {
        Files.createDirectories(tempDir.resolve("src/main/java/com/acme/order/domain"));
        Files.createDirectories(tempDir.resolve("src/main/java/com/acme/order/controller"));
        Files.createDirectories(tempDir.resolve("src/test/java/com/acme/order"));

        Files.writeString(tempDir.resolve("pom.xml"), """
                <project>
                    <modelVersion>4.0.0</modelVersion>
                    <properties>
                        <java.version>11</java.version>
                        <spring-boot.version>2.7.18</spring-boot.version>
                    </properties>
                    <dependencies>
                        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-web</artifactId></dependency>
                        <dependency><groupId>org.springframework.boot</groupId><artifactId>spring-boot-starter-security</artifactId></dependency>
                    </dependencies>
                </project>
                """);

        Files.writeString(tempDir.resolve("src/main/java/com/acme/order/domain/OrderEntity.java"), """
                package com.acme.order.domain;

                import javax.persistence.Entity;

                @Entity
                class OrderEntity {
                }
                """);

        Files.writeString(tempDir.resolve("src/main/java/com/acme/order/controller/OrderController.java"), """
                package com.acme.order.controller;

                import org.springframework.web.bind.annotation.RestController;

                @RestController
                class OrderController {
                }
                """);

        Files.writeString(tempDir.resolve("src/test/java/com/acme/order/OrderControllerTest.java"), """
                package com.acme.order;

                import org.springframework.boot.test.mock.mockito.MockBean;

                class OrderControllerTest {
                    @MockBean
                    Object dependency;
                }
                """);

        var architect = new ProjectScanService(GuardianSettings.defaults()).scan(tempDir).architectMode();

        assertTrue(architect.productionReadiness().score() < 100);
        assertTrue(architect.productionReadiness().risks().stream().anyMatch(risk -> risk.toLowerCase().contains("actuator")));

        assertTrue(architect.upgradePath().steps().stream().anyMatch(step -> step.title().contains("Java 17")));
        assertTrue(architect.upgradePath().steps().stream().anyMatch(step -> step.title().contains("Spring Boot 3")));
        assertTrue(architect.upgradePath().steps().stream().anyMatch(step -> step.title().contains("jakarta")));

        String yaml = architect.openRewritePlan().yaml();
        assertTrue(yaml.contains("recipeList"));
        assertTrue(yaml.contains("org.openrewrite.java.spring.boot3.UpgradeSpringBoot_3_0"));
        assertTrue(yaml.contains("org.openrewrite.java.migrate.jakarta.JavaxMigrationToJakarta"));
        assertTrue(architect.modernizationPlan().markdown().contains("Spring Guardian Modernization Plan"));
    }
}
